# Generated by Django 4.1.7 on 2023-03-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_team_abbreviation"),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="team1",
        ),
        migrations.RemoveField(
            model_name="match",
            name="team2",
        ),
        migrations.AddField(
            model_name="match",
            name="away",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="away_team",
                to="team.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="home",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_team",
                to="team.team",
            ),
        ),
    ]
