# Generated by Django 4.1.7 on 2023-03-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_seasonprofile_gameweek"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_start",
            field=models.BooleanField(default=False),
        ),
    ]
