# Generated by Django 4.1.7 on 2023-03-07 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_profile_is_start"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameweek",
            options={
                "ordering": ("id",),
                "verbose_name": "game week",
                "verbose_name_plural": "games week",
            },
        ),
        migrations.AlterModelOptions(
            name="seasonprofile",
            options={
                "ordering": ("id",),
                "verbose_name": "profile season",
                "verbose_name_plural": "profiles season",
            },
        ),
        migrations.AlterModelTable(
            name="gameweek",
            table="db_game_week",
        ),
        migrations.AlterModelTable(
            name="seasonprofile",
            table="db_season_profile",
        ),
    ]
