# Generated by Django 4.1.7 on 2023-03-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_gameweek_options_alter_seasonprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameweek",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
