version: "3.7"

services:
  db:
    image: postgres
    container_name: database_nfl
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=nfl_user
      - POSTGRES_PASSWORD=nfl_password
      - POSTGRES_DB=db_nfl
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
