# Generated by Django 4.1.7 on 2023-02-15 04:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logo', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'conferecy',
                'verbose_name_plural': 'conferencies',
                'db_table': 'db_conferency',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conferency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_conferency', to='team.conferency')),
            ],
            options={
                'verbose_name': 'division',
                'verbose_name_plural': 'divisions',
                'db_table': 'db_division',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stadium', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=250)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_division', to='team.division')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'db_table': 'db_team',
                'ordering': ('id',),
            },
        ),
    ]
