# Generated by Django 4.1.7 on 2023-03-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="primary_color",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="secondary_color",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
