# Generated by Django 4.1.7 on 2023-03-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="abbreviation",
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
