# Generated by Django 4.1.7 on 2023-02-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_week_match_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='profile',
        ),
    ]
