# Generated by Django 4.1.7 on 2023-02-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_match_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='profile',
        ),
    ]
